import getWeather from "./api.js";
import radioChange from "./radio.js";
export default function getWeatherUi() {
  const txtCity = document.createElement("input");
  const btnGetWeather = document.createElement("button");
  const getWeatherDiv = document.createElement("div");
  const divResult = document.createElement("div");
  document.body.append(getWeatherDiv);
  txtCity.type = "text";
  btnGetWeather.textContent = "Search City";
  txtCity.classList.add("txt-city");
  getWeatherDiv.classList.add("div-get-weather");
  btnGetWeather.addEventListener("click", getWeather);
  const spanName = document.createElement("span");
  const spanTemp = document.createElement("span");
  const spanFeels = document.createElement("span");
  const spanDesc = document.createElement("span");
  const divMetric = document.createElement("div");
  const divImperial = document.createElement("div");
  const divInput = document.createElement("div");
  divInput.append(txtCity);
  divInput.append(btnGetWeather);
  getWeatherDiv.append(divInput);
  divResult.append(spanName);
  divResult.append(spanDesc);
  divResult.append(spanTemp);
  divResult.append(spanFeels);
  spanName.classList.add("spn-name");
  spanDesc.classList.add("spn-desc");
  spanTemp.classList.add("spn-temp");
  spanFeels.classList.add("spn-feels");
  const unitMetric = document.createElement("input");
  const imperialLabel = document.createElement("Label");
  const metricLabel = document.createElement("Label");
  const unitimperial = document.createElement("input");
  unitMetric.type = "radio";
  unitimperial.type = "radio";
  divImperial.append(unitimperial);
  divImperial.append(imperialLabel);
  divMetric.append(unitMetric);
  divMetric.append(metricLabel);
  unitimperial.value = "imperial";
  unitMetric.value = "metric";
  unitMetric.name = "unit";
  unitMetric.checked = true;
  unitimperial.name = "unit";
  metricLabel.setAttribute("for", "rad-metric");
  metricLabel.textContent = "Metric";
  imperialLabel.setAttribute("for", "rad-imperial");
  imperialLabel.textContent = "Imperial";
  unitMetric.id = "rad-metric";
  unitimperial.id = "rad-imperial";
  unitMetric.addEventListener("change", radioChange);
  unitimperial.addEventListener("change", radioChange);
  divInput.append(divMetric);
  divInput.append(divImperial);
  divMetric.classList.add("div-metric");
  divImperial.classList.add("div-imperial");
  getWeatherDiv.append(divInput);
  divInput.classList.add("div-input");
  getWeatherDiv.append(divResult);
  divResult.classList.add("div-result");
}
